"""Replaceable ports for durable bulk state, artifacts, and notifications."""

from datetime import datetime, timedelta
from typing import Protocol, TypeVar

from ai_retrieval.bulk.models import (
    BrokerDelivery,
    BulkStateTelemetry,
    CheckpointRecord,
    CheckpointStage,
    DeadLetterEntry,
    JobTerminalCause,
    ObjectReference,
    OutboxRecord,
    PersistenceFailureOutcome,
    ResumeState,
    TerminalJobReport,
    TerminalWorkItemRecord,
    TerminalWorkItemState,
    WorkClaim,
    WorkItemExecutionResult,
    WorkItemRecord,
    WorkNotification,
)
from ai_retrieval.bulk.effect_models import (
    EffectAttempt, EffectEvidence, EffectRecord, EffectRequest, ReconciliationRecord,
)
from ai_retrieval.domain.execution import ExecutionContext
from ai_retrieval.domain.work import BatchJob


T_co = TypeVar("T_co", covariant=True)


class BulkDispatcher(Protocol[T_co]):
    def dispatch(self, job: BatchJob, context: ExecutionContext) -> T_co: ...


class DurableWorkRepository(Protocol):
    def create_with_outbox(self, item: WorkItemRecord, outbox: OutboxRecord) -> WorkItemRecord: ...
    def item(self, job_id: str, idempotency_key: str) -> WorkItemRecord | None: ...
    def items(self, job_id: str) -> tuple[WorkItemRecord, ...]: ...
    def claim(self, job_id: str, idempotency_key: str, owner: str, now: datetime, lease_duration: timedelta) -> WorkClaim: ...
    def renew(self, job_id: str, idempotency_key: str, owner: str, now: datetime, lease_duration: timedelta) -> WorkItemRecord: ...
    def checkpoint(self, job_id: str, idempotency_key: str, owner: str, stage: CheckpointStage, outcome: str, now: datetime, result_reference: ObjectReference | None = None) -> CheckpointRecord: ...
    def resume_state(self, job_id: str, idempotency_key: str) -> ResumeState: ...
    def pending_outbox(self) -> tuple[OutboxRecord, ...]: ...
    def mark_published(self, event_id: str, at: datetime) -> OutboxRecord: ...
    def terminalize(self, job_id: str, idempotency_key: str, owner: str, state: TerminalWorkItemState, failure_code: str | None, failure_details: str | None, now: datetime, result_reference: ObjectReference | None = None) -> TerminalWorkItemRecord: ...
    def terminal_items(self, job_id: str) -> tuple[TerminalWorkItemRecord, ...]: ...
    def record_persistence_failure(self, outcome: PersistenceFailureOutcome) -> None: ...
    def persistence_failures(self, job_id: str) -> tuple[PersistenceFailureOutcome, ...]: ...


class DeadLetterQueue(Protocol):
    def persist(self, entry: DeadLetterEntry) -> DeadLetterEntry: ...
    def entries(self, job_id: str) -> tuple[DeadLetterEntry, ...]: ...


class BulkTelemetrySink(Protocol):
    def job_state_changed(self, telemetry: BulkStateTelemetry) -> None: ...


class TerminalJobReporter(Protocol):
    def report(self, job_id: str, cause: JobTerminalCause, now: datetime) -> TerminalJobReport: ...


class WorkItemHandler(Protocol):
    def execute(self, item: WorkItemRecord) -> WorkItemExecutionResult: ...


class ObjectResultStore(Protocol):
    def put_payload(self, data: bytes) -> ObjectReference: ...
    def put_result(self, data: bytes) -> ObjectReference: ...
    def get(self, reference: ObjectReference) -> bytes: ...


class NotificationBroker(Protocol):
    def publish(self, notification: WorkNotification) -> None: ...
    def receive(self) -> BrokerDelivery | None: ...
    def acknowledge(self, delivery_id: str) -> bool: ...


class EffectRecoveryRepository(Protocol):
    def effect(self, job_id: str, idempotency_key: str) -> EffectRecord | None: ...
    def save_effect(self, record: EffectRecord) -> EffectRecord: ...
    def save_reconciliation(self, record: ReconciliationRecord) -> ReconciliationRecord: ...
    def reconciliation(self, job_id: str, idempotency_key: str) -> ReconciliationRecord | None: ...


class EffectAdapter(Protocol):
    """Target-side idempotency contract.

    Shared execution MUST commit the mutation and effect record atomically. Any failure
    before commit MUST roll back every transaction change before returning ROLLED_BACK
    or raising. Non-shared execution has the equivalent all-or-nothing mutation duty.
    """

    def execute_shared(self, request: EffectRequest, context: ExecutionContext) -> EffectEvidence: ...
    def verify_effect(self, idempotency_key: str, mutation_digest: str, context: ExecutionContext) -> EffectEvidence: ...
    def execute_non_shared(self, effect, mutation_digest: str, context: ExecutionContext) -> EffectAttempt: ...
